# Generated by Django 5.1.7 on 2025-03-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
    ]
