# Generated by Django 5.1.7 on 2025-03-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_remove_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
